//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.23 at 03:06:57 AM GMT+03:00 
//


package ru.ma.boldyrev.spring2.soap.source_of_earning;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.ma.boldyrev.spring2.soap.source_of_earning package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.ma.boldyrev.spring2.soap.source_of_earning
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestRequest }
     * 
     */
    public TestRequest createTestRequest() {
        return new TestRequest();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link PingResponse }
     * 
     */
    public PingResponse createPingResponse() {
        return new PingResponse();
    }

    /**
     * Create an instance of {@link CreateSourceOfEarningRequest }
     * 
     */
    public CreateSourceOfEarningRequest createCreateSourceOfEarningRequest() {
        return new CreateSourceOfEarningRequest();
    }

    /**
     * Create an instance of {@link CreateSourceOfEarningResponse }
     * 
     */
    public CreateSourceOfEarningResponse createCreateSourceOfEarningResponse() {
        return new CreateSourceOfEarningResponse();
    }

    /**
     * Create an instance of {@link RemoveSourceOfEarningRequest }
     * 
     */
    public RemoveSourceOfEarningRequest createRemoveSourceOfEarningRequest() {
        return new RemoveSourceOfEarningRequest();
    }

    /**
     * Create an instance of {@link RemoveSourceOfEarningResponse }
     * 
     */
    public RemoveSourceOfEarningResponse createRemoveSourceOfEarningResponse() {
        return new RemoveSourceOfEarningResponse();
    }

    /**
     * Create an instance of {@link GetListOfSourceOfEarningRequest }
     * 
     */
    public GetListOfSourceOfEarningRequest createGetListOfSourceOfEarningRequest() {
        return new GetListOfSourceOfEarningRequest();
    }

    /**
     * Create an instance of {@link GetListOfSourceOfEarningResponse }
     * 
     */
    public GetListOfSourceOfEarningResponse createGetListOfSourceOfEarningResponse() {
        return new GetListOfSourceOfEarningResponse();
    }

    /**
     * Create an instance of {@link SourceOfEarningRecord }
     * 
     */
    public SourceOfEarningRecord createSourceOfEarningRecord() {
        return new SourceOfEarningRecord();
    }

    /**
     * Create an instance of {@link ResultRecord }
     * 
     */
    public ResultRecord createResultRecord() {
        return new ResultRecord();
    }

}
