//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.23 at 03:06:57 AM GMT+03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://boldyrev.ma.ru/spring2/soap/source-of-earning", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.ma.boldyrev.spring2.soap.source_of_earning;
